all: dynamic dynamic2 dynamic3 train

dynamic: dynamic.c
	gcc dynamic.c -o dynamic.o
dynamic2: dynamic2.c
	gcc dynamic2.c -o dynamic2.o
dynamic3: dynamic3.c
	gcc dynamic3.c -o dynamic3.o
train: train.c
	gcc train.c -o train.o
clean:
	rm *.o
